### ISSUE TITLE
Reimplement the svf method based on the PFENet code and the result is inferior than original PFENet.

### ISSUE THREAD

**Issue by lyphui** [zechao-li/SVF-pytorch#1]
Thanks for your nice work. I implement the svf method based on the PFENet code and the result is inferior than original PFENet. I followed the parameter setting in PFENet. And I used the same dataset and parameter setting in both **original PFENet** and **PFENet with SVF**. But the performance of PFENet with SVF performs worse than original PFENet. Could you please share your full-training code  rather than svf module code? Thanks a lot!

**Comment by syp2ysy** [comment]
@lyphui The reason for this is detailed in this issue _https://github.com/syp2ysy/SVF/issues/3_  and the code of FSSS is  https://github.com/zechao-li/SVF-few-shot-segmentation
